debug_level: "INFO"

mqtt:

  host: "192.168.0.168" # Endereço do broker MQTT

  port: 1883 # Porta do broker MQTT

  keepalive: 0 # Intervalo de keepalive em segundos (0 desativa o timeout)

  qos: 1 # Nível de QoS (Quality of Service)
  
  topics:
    system_telemetry: 
      - mac_address
      - timestamp
      - uptime_ms
      - cpu_frequency
      - ram_usage
      - temp
      - wifi_ssid
      - wifi_signal
      - ip
      - sketch_md5
      # - battery_level

    logs:
      - mac_address
      - timestamp
      - code
      - message

    spectrum_datapoints:
      - mac_address
      - timestamp
      - batch
      - flag
      - led_color
      - led_intensity
      - channel_415nm
      - channel_445nm
      - channel_480nm
      - channel_515nm
      - channel_555nm
      - channel_590nm
      - channel_630nm
      - channel_680nm
      - channel_clear
      - channel_nir

system: WINDOWS
# system: LINUX

sqlite_web_interface: false
app_web_interface: true

nfc:
  nfc_timeout: 20 # Tempo limite em segundos para leitura NFC (0 desativa o timeout)

presence_sensor:
  ld2410_device_path: "/dev/ttyS0" # Caminho do dispositivo do sensor LD2410
  near_threshold_cm: 120 # Distância em centímetros para detectar presença próxima
  in_use_threshold_cm: 60 # Distância em centímetros para detectar uso do mictório

web_interface:
  launch_browser_on_start: true
  host: "localhost"
  port: 5000
  main_page: "welcome"
